name: CI/CD
on:
  push:
    branches: ["main"]
    paths: ['src/**', 'Containerfile']
  workflow_dispatch: 
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
        id: buildx
      - uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/build-push-action@v6.7.0
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: .
          file: "Containerfile"
          push: true
          load: true
          tags: "ghcr.io/${{ github.repository }}"
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache